version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3005:3005"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./backend/enterprise.db:/usr/src/app/enterprise.db
      - ./backend/system.log:/usr/src/app/system.log

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
